name: JustWatch CI/CD

run-name: ${{ github.actor }} is testing out Github Actions!

env:
  # The name of the main module repository
  main_project_module: app

  # The name of the Play Store
  playstore_name: JustWatch

on:
  push:
    branches: [ "master" ]

jobs:
  Just-Watch-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Invalidate Gradle Cache
        run: ./gradlew --refresh-dependencies

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test Results
          path: app/build/test-results/testDebugUnitTest/

      - name: Upload Unit Test Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: Unit Test HTML Report
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Build gradle project
        run: ./gradlew build

      - name: Create APK
        run: ./gradlew assembleRelease

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.playstore_name }} - APK(s) release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/
